config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"

  resources :articles
  resources :users, except: [:new]

  get "about", to: "pages#about"
  get "signup", to: "users#new"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories

    validates :name, presence: true, length: { minimum:3, maximum:25 }
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                uniqueness: { case_sensetive: false }, 
                length: { minimum:3, maximum:25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, 
                uniqueness: { case_sensetive: false }, 
                length: { maximum:105 },
                format: { with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to peform that action"
            redirect_to login_path
    
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :destroy, :update, :edit]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :destroy, :update]
    
    def show

    end

    def index
        @articles = Article.paginate(:page => params[:page], :per_page => 5)
    end

    def new
        @article = Article.new
        
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit

    end

    def update

        if @article.update(article_params)
            flash[:notice] = "Article was edited successfully."
            redirect_to @article
        else
            render 'edit', status: :unprocessable_entity
        end 
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [] )
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own articles"
            redirect_to @article
        end


    end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update]
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new

    end

    def show
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new', status: :unprocessable_entity 
        end
    end

    def edit

    end

    def update
        if @category.update(category_params)
            flash[:notice] = "Category was edited successfully."
            redirect_to @category
        else
            render 'edit', status: :unprocessable_entity
        end 
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end

    def set_category
        @category = Category.find(params[:id])
    end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end

    def about
        
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your credentials"
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def show
        @articles = @user.articles.paginate(:page => params[:page], :per_page => 5)
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to Alpha Blog, you have successfully signed up!"
            redirect_to '/'
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit

    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def index      
        @user = User.paginate(:page => params[:page], :per_page => 5)
    end

    def login
    
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account successfully deleted."
        redirect_to '/'
    end


    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if !(logged_in? && current_user == @user) && !current_user.admin? 
            flash[:alert] = "You can only edit your profile"
            redirect_to @user
        end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size:80 })
       email_address = user.email.downcase
       hash = Digest::MD5.hexdigest(email_address)
       size = options[:size]
       gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
       return image_tag(gravatar_url, alt: user.username, class:"rounded shadow mx-auto d-block")
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card shadow mb-4 bg-white rounded text-center">
                <div class="card-header fst-italic">
                    <%= gravatar_for article.user %>
                    by <%= link_to (article.user.username if article.user), article.user %>
                    <% if article.categories.any? %>
                        </br>
                        <div class="mt-2"><%= render article.categories %></div> 
                    <% end %>
                </div>

                <div class="card-body">
                    <div class="card-text text-start"><%= simple_format(article.description) %></div>
                    <%= link_to "View", article_path(article), class:"btn btn-outline-success"%>
                    <% if logged_in? %>
                        <% if current_user == article.user || current_user.admin? %>
                            <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info"%>
                            <%= link_to "Delete", article_path(article), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure you want to delete this article ?"}, class:"btn btn-outline-danger"%>
                        <% end %>
                    <% end %>
                </div>

                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
                    edited <%= time_ago_in_words(article.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container"> 
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
            <%= form_with(model: @article, local:true, class:'bg-secondary font-white shadow p-3 mb-4 rounded') do |f| %>
                <div class="form-group mb-4 justify-content-center">
                    <%= f.label :title, class:"col-2 col-form-label text-light" %>
                    <div class="text-center">
                        <%= f.text_field :title, class:"form-control", placeholder:"Article's title" %>
                    </div>
                    
                </div>

                <div class="form-group mb-4">
                    <%= f.label :description, class:"text-light" %> <br/>
                    <%= f.text_area :description, rows: 10, class:"form-control", placeholder:"Description of article" %>
                    
                </div>


                <div class="form-group mb-4">
                    <div class="row">
                        <div class="col-sm-offset-2">
                            <%= f.label :category_ids, class:"text-light" %> <br/>
                            <%= f.collection_select :category_ids, Category.all, :id, :name,
                            { prompt: "Make your selection from the list below (can be empty)" }, { multiple: true, class: "form-select shadow rounded" } %>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-4">    
                    <%= f.submit class:"btn btn-success" %>
                </div> 
            <% end %>
        </div>
    
    </div>
    <%= link_to '[Cancel and return back to all articles]', articles_path, class:"text-info"%>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Edit article</h1>

    <%= render 'form' %>

</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title  %></h1>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card shadow mb-4 bg-white rounded text-center">
                <div class="card-header fst-italic">
                    <%= link_to gravatar_for(@article.user), @article.user, class: "mb-4 shadow" %>
                    by <%= link_to (@article.user.username if @article.user), @article.user %>
                    <% if @article.categories.any? %>
                        </br>
                        <div class="mt-2"><%= render @article.categories %></div> 
                    <% end %>
                    
                </div>
                
                <div class="card-body">
                    <div class="card-text text-start"><%= simple_format(@article.description) %></div>
                    <% if logged_in? %>
                        <% if current_user == @article.user || current_user.admin? %>
                            <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info"%>
                            <%= link_to "Delete", article_path(@article), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure you want to delete this article ?"}, class:"btn btn-outline-danger"%>
                        <% end %>
                    <% end %>
                </div>

                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
                    edited <%= time_ago_in_words(@article.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>


app/views/categories/_category.html.erb
<%= link_to category.name,  category_path(category), class: "badge rounded-pill bg-primary ms-1" %>

app/views/categories/_form.html.erb
<div class="container"> 
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @category %>
            <%= form_with(model: @category, local:true, class:"bg-secondary font-white shadow p-3 mb-4 rounded") do |f| %>
                <div class="form-group mb-4">
                    <%= f.label :name, class:"col-2 col-form-label text-light" %>
                    <div class="text-center">
                        <%= f.text_field :name, class:"form-control", placeholder:"Enter category name" %>
                    </div>
                </div>

                <div class="form-group mb-4">    
                    <%= f.submit class:"btn btn-success" %>
                </div> 
            <% end %>
        </div>
        <%= link_to '[Cancel and return back to all articles]', articles_path, class:"text-info text-center text-black"%>
    </div>
</div>

app/views/categories/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Edit category</h1>

    <%= render 'form' %>

</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">All categories</h1>


<% @categories.each do |category| %>
    <div class="row justify-content-md-center">
        <div class="col-3 mt-4">
            <div class="card shadow mb-4 bg-white rounded text-center">
                <div class="card-body ">
                    <h5 class="card-title"><%= link_to category.name, category_path(category.id) %></h5>
                    <div class="card-text text-center mt-2"><%= pluralize(category.articles.count, "article") %></div>
                </div>
                
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(category.created_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
<% end %>


<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @categories %>
    </div>
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4">Create a new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 mb-4">Category: <%= @category.name %>!</h1>



<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
      <%= link_to "Edit category name", edit_category_path(@category), class:"btn btn-info font-black" %>
    </div>

    <div class="text-center mt-2">
        <%= link_to "Delete category", category_path(@category), 
        data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure you want to delete this category?"
        }, 
        class:"btn btn-danger font-black" %>
    </div>
<% end %>

<div class="card-text text-center  mt-2">
    <%= pluralize(@category.articles.count, "article") %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_messages.html.erb
<div class="container col-6 rounded mb-2 mt-2">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="success" aria-label="Close"></button>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-dark navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">

            <%= link_to "RAILS BLOG", root_path, class: "navbar-brand", id:"logo" %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Bloggers", users_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Articles
                        </a>
                        <ul class="dropdown-menu">
                            <% if logged_in? %>
                                <li><%= link_to "Create a new article" , new_article_path, class:"dropdown-item"%></li>
                            <% end %>
                            <li><%= link_to "View articles" , articles_path, class:"dropdown-item"%></li>
                            

                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "View Categories" , categories_path, class:"dropdown-item"%></li>
                            <% if logged_in? %>
                                <% if current_user.admin? %>
                                    <li><%= link_to "Create a new category" , new_category_path, class:"dropdown-item"%></li>
                                <% end %>
                            <% end %>                         
                        </ul>
                    </li>

                    <% if logged_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "View your profile" , user_path(current_user.id), class:"dropdown-item"%></li>
                            <li><%= link_to "Edit your profile" , edit_user_path(current_user.id), class:"dropdown-item"%></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Coming soon!</a></li>
                        </ul>
                    </li>
                        <li class="nav-item">
                            <%= link_to "Logout", logout_path, class: "nav-link", data: {turbo_method: :delete} %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to "Log In", login_path, class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Sign up", signup_path, class: "nav-link" %>
                        </li>
                    <% end %>
                </ul>

            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search for an article" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
    </nav>

app/views/layouts/_sticky_footer.html.erb
<footer id="sticky-footer" class="footer d-flex column mt-auto py-3 bg-dark text-center" >
    <div class="container">
        <span class="text-light">Giorgos Panaretou since 1997.</span>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RAILS7 BLOG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/sticky_footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<ul>
    <li><%= link_to 'Home', root_path%></li>
</ul>

app/views/pages/home.html.erb
<div class="container" id="home-container">
   
    <div class="row justify-content-center">        
        <div class="col-6">
            <div class="p-3 mb-3  bg-light rounded-3">
                <div class="container-fluid py-4">
                    <div class="col">
                        <h1 class="display-5 fw-bold">Rails Blog</h1>
                        <p class="fs-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor at risus viverra adipiscing at in tellus integer. Sagittis id consectetur purus ut faucibus pulvinar.</p>
                        <%= link_to "Sign up!", signup_path, class:"btn btn-primary btn-lg" %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-10">
            <div class="p-2 mb-3  bg-light rounded-3">
                <div class="container-fluid py-4">
                    <div class="text-center" id="home-page-image">
                        <img src="" alt=" " class="rounded">
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container">
    <div class="alert alert-dismissible fade show shadow p-3 mb-4 rounded" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <h3 class="alert-danger text-center">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h3>
        <ol>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ol>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container"> 
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with(model: @user, local:true, class:"bg-secondary font-white shadow p-3 mb-4 rounded") do |f| %>
                <div class="form-group mb-4">
                    <%= f.label :username, class:"col-2 col-form-label text-light" %>
                    <div class="text-center">
                        <%= f.text_field :username, class:"form-control", placeholder:"Enter you username" %>
                    </div>
                </div>

                <div class="form-group mb-4">
                    <%= f.label :email, class:"text-light" %> <br/>
                    <%= f.email_field :email, class:"form-control", placeholder:"Enter your email" %>
                </div>
                <div class="form-group mb-4">
                    <%= f.label :password, class:"text-light" %> <br/>
                    <%= f.password_field :password, class:"form-control", placeholder:"Enter your password" %>
                </div>

                <div class="form-group mb-4">    
                    <%= f.submit(@user.new_record? ? "Sign up!" : "Update account", class:"btn btn-success") %>
                </div> 
            <% end %>
        </div>
        <%= link_to '[Cancel and return back to all articles]', articles_path, class:"text-info text-center text-black"%>
    </div>
</div>

app/views/users/_user.html.erb
<div class="container">
    <% @user.each do |user| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card shadow mb-4 bg-white rounded text-center">
                <div class="card-header fst-italic">
                    <%= link_to user.username, user %>
                </div>

                <div class="card-body">
                    <%= gravatar_for user, size: 200 %>
                    
                    <div class="card-text text-center fst-italic mt-2"><%= pluralize(user.articles.count, "article") %></div>
                    <%= link_to "View", user_path(user), class:"btn btn-outline-success mt-2" %>
                    <% if logged_in? %>
                        <% if current_user == user %>
                            <%= link_to "Edit", edit_user_path(user), class:"btn btn-outline-info mt-2"%> 
                        <% end %>
                        
                            <% if current_user == user || current_user.admin? %>
                                <%= link_to "Delete", user_path(user), data: {
                                    turbo_method: :delete,
                                    turbo_confirm: "Are you sure you want to delete this user ?"}, class:"btn btn-outline-danger mt-2" %>
                            <% end %>
                    <% end %>
                </div>

                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(user.created_at) %> ago, 
                    edited <%= time_ago_in_words(user.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit user settings</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4">All users</h1>

<%= render 'user' %>

<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @user %>
    </div>
    <%= will_paginate @user, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4 mb-4">Sign up!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4 mb-4">Hi <%= @user.username %>!</h1>

<%= gravatar_for @user , size: 200 %>

<% if logged_in? %>
  <% if current_user == @user %>
    <div class="text-center mt-4">
      <%= link_to "Edit profile", edit_user_path(@user), class:"btn btn-info font-black" %>
    </div>
  <% end %>

  <% if current_user == @user || current_user.admin? %>
      <div class="text-center mt-2">
          <%= link_to "Delete profile", user_path(@user), 
            data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure you want to delete this account and all associated articles?"
            }, 
          class:"btn btn-danger font-black" %>
      </div>
  <% end %>
<% end %>

<h3 class="text-center mt-4">Articles by <%= @user.username %></h3>

<div class="card-text text-center fst-italic mt-2"><%= pluralize(@user.articles.count, "article") %></div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>